In [1]:
num=list(map(str,input('enter the numbers').split(" ")))
sum=0
for i in num:
    x=int(i[1])
    sum=sum+x
print(sum)    

enter the numbers123 123 123
6


num

## data analysis
- any useful information is called as data
- types of data in devices
   - .txt,.img,.ppt,.mp3,.excel,.doc etc
- types of data in realtime
    1. quantitative data 
         - represents the size/volume of data
     types 
      -discrete .... data is constant or fixed.example:numbers in a dice,colour nationality etc
      -continuos....value or data is not fixed(changes after a period of time)example:time,height,weight
    2. qualitative data
      - data is analysed and categorised
         ex:data submission in feedback form



- DATA IN STATISTICS
  -nominal,ordinal,interval and ratio
   - NOMINAL:data is categorised on the basis of names.example:color,nationality,gender
   - ORDINAL:data is categorised on the basis of order of value.example:feedback form
   - INTERVAL:a range of interval values.example:time interval in clock
   - RATIO:data is meaningfully adde,subtracted,multiplied(ratios)

In [2]:
## numpy
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [3]:
np.__version__

'1.20.1'

#### "numpy" means numerical python which is used to deal with array and scientific calculations
- array(): method to create an array
  syntax:numpy.array([itterable])
- array.ndim:get dimensions of array
- size:used to get no of elements
- shape :used to get the rows and columns
- dtype:used to check the datatype
  

In [4]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.array(('abc','def'))

array(['abc', 'def'], dtype='<U3')

In [6]:
np.array([1,2.5,4.9,5],dtype="float")

array([1. , 2.5, 4.9, 5. ])

In [7]:
np.array([1,2.5,4.9,5],dtype="int")

array([1, 2, 4, 5])

In [8]:
np.array([1,2.3,'abc'],dtype="str")

array(['1', '2.3', 'abc'], dtype='<U3')

In [9]:
a=np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b=np.array(range(10,101))
b

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
a=np.array(range(1,51,3))
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [12]:
a=np.array(range(100,49,-1))
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50])

In [13]:
a=np.array(range(50,0,-3))
a

array([50, 47, 44, 41, 38, 35, 32, 29, 26, 23, 20, 17, 14, 11,  8,  5,  2])

In [14]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.ndim #dimensions

2

In [16]:
b.size #no of elements

6

In [17]:
b.shape #returns rows and columns

(2, 3)

In [18]:
b.dtype #used to check the datatype

dtype('int32')

In [19]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
c


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
c.ndim

3

In [21]:
c.size

12

In [22]:
c.shape

(3, 2, 2)

In [23]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[0]

1

In [24]:
b=np.array([[1,2,3],[4,5,6]])
b[0,0]

1

In [25]:
# n-d arrays
a=np.array([3,4,5,6,5],ndmin=4)
a

array([[[[3, 4, 5, 6, 5]]]])

- creating another arrays
-- eye(num):creates the identity matrics of num dimensions
-- zeros() method is used to create null matrics
- ones(dimensions,dtype="datatype")
-- arange() function to create the array to 

In [26]:
i=np.eye(3) # identity matrics
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a=np.zeros((3,3)) #null matrics
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
a=np.ones(5,dtype="int")
a

array([1, 1, 1, 1, 1])

In [29]:
o=np.ones((3,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
a=np.full(3,"hi")
a

array(['hi', 'hi', 'hi'], dtype='<U2')

In [31]:
b=np.full((3,3),"hello")
b

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']], dtype='<U5')

In [32]:
b.fill(4)
b

array([['4', '4', '4'],
       ['4', '4', '4'],
       ['4', '4', '4']], dtype='<U5')

In [33]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
a=np.arange(20,100,4)
a

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84,
       88, 92, 96])

In [37]:
a=np.arange(100,0,-1)
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

# constructing a 2d array using 1d array

In [38]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.reshape(2,6) # only multiples of the size of the array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [42]:
b=np.arange(100,20,-4)
b

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24])

In [43]:
b.reshape(4,5)

array([[100,  96,  92,  88,  84],
       [ 80,  76,  72,  68,  64],
       [ 60,  56,  52,  48,  44],
       [ 40,  36,  32,  28,  24]])

# random
- module in python to generate random numbers
- example otp
-- randint is a method to generate the random integers
-- random.randon((a,b)) here a and b are size of aray and the range is 0 to 1
-random.randn(a,b) here a and b are size of aray and the range is -1 to 1
-np.linspace(a,b) into 50 partition and the range of 50 elements are in a,b

In [45]:
a=np.random.randint(20)
a

9

In [49]:
b=np.random.randint(10,100)
b

51

In [55]:
lw,uw=int(input()),int(input())
a=np.random.randint(lw,uw,8)
a.reshape(2,4)

2
200


array([[ 10,  62, 189, 126],
       [ 84, 163, 139,  35]])

In [58]:
a=np.random.random((2,3))
a

array([[0.82622768, 0.13731659, 0.63346068],
       [0.29867391, 0.52667131, 0.81366119]])

In [60]:
a=np.random.randn(2,3)
a

array([[-0.73316355, -0.15115498,  0.13245793],
       [ 1.87053206, -0.84970017,  0.52971146]])

In [61]:
a=np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [63]:
np.size(a)

50

In [70]:
b=np.arange(12).reshape(3,4)
print(b)
print("----transpose----")
print(b.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----transpose----
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [77]:
b=np.arange(10).reshape(2,5)
print(b)
print("--slice--")
print(b[0,0:2])
print(b[1,1:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
--slice--
[0 1]
[6 7]


In [78]:
a=np.random.randint(20,40,8)
a.reshape(2,4)

array([[30, 26, 30, 25],
       [39, 23, 32, 30]])

In [79]:
b=np.random.randint(10,20,8)
b.reshape(2,4)

array([[13, 19, 18, 14],
       [10, 10, 18, 11]])

In [94]:
print("--ADDITION--")
c=a+b
print(c.reshape(2,4))
print("--subtraction--")
d=a-b
print(d.reshape(2,4))
print("--multiplication--")
m=a*b
print(m.reshape(2,4))
print("--division--")
div=(a/b)
print(div.reshape(2,4))


--ADDITION--
[[43 45 48 39]
 [49 33 50 41]]
--subtraction--
[[17  7 12 11]
 [29 13 14 19]]
--multiplication--
[[390 494 540 350]
 [390 230 576 330]]
--division--
[[2.30769231 1.36842105 1.66666667 1.78571429]
 [3.9        2.3        1.77777778 2.72727273]]


--scientific calculation

In [95]:
np.log(1)

0.0

In [96]:
a=np.log([1,2,3,4])
a

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [98]:
a=np.sin([1,2,3])
a

array([0.84147098, 0.90929743, 0.14112001])

# statistics

In [104]:
a=np.array([[17,784,45,2],[45,48,25,95]])
print(a)
print("minimum element is:",np.amin(a))
print("maximum element is:",np.amax(a))

[[ 17 784  45   2]
 [ 45  48  25  95]]
minimum element is: 2
maximum element is: 784


In [111]:
a=np.array([5,4,6])
print("mean:",np.mean(a))
print("median:",np.median(a))

mean: 5.0
median: 5.0


## standard deviation
- it is the square root of average of square deviations of mean

In [112]:
print("standard deviation:",np.std(a))

standard deviation: 0.816496580927726


## variance
- average of squares of standard deviations

In [113]:
print("variance",np.var(a))

variance 0.6666666666666666


### remaining methods in aggregation

In [120]:
a=np.array([[17,784,45,2],[45,48,25,95]])
print(a)
print("index of minimum value in array",np.argmin(a))
print("index of maximum value in array",np.argmax(a))

[[ 17 784  45   2]
 [ 45  48  25  95]]
index of minimum value in array 3
index of maximum value in array 1


In [122]:
np.percentile(a,10)

12.5

In [131]:
a=np.array([1,2,3,4])
print(a)
print("product:",a.prod())
print("sum:",a.sum())

[1 2 3 4]
product: 24
sum: 10


## filtering

In [132]:
a=np.array([42,43,44,45,41])
f=a>42
n=a[f]
print(f)
print(n)

[False  True  True  True False]
[43 44 45]


In [135]:
a=np.array([2,4,6,10,7,11,13])
even=(a%2==0)
n=a[even]
print(n)

[ 2  4  6 10]


### saving the data
- inport 2 modules from numpy they are:
             1.asarray
             2.savetxt

In [137]:
from numpy import asarray
from numpy import savetxt
data=np.array([[1,2,3,4],[5,6,7,8]])
savetxt('data.csv',data,delimiter=",")

#### displaying the data from .csv file


In [141]:
from numpy import loadtxt
data=loadtxt('data.csv',delimiter=",")
data

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])